MovieArchiveTemplate/Controllers/MembershipController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using MovieArchiveTemplate.Models;
using MovieArchiveTemplate.Models.HelperModels;
using MovieArchiveTemplate.Models.ViewModels;
using MovieArchiveTemplate.Repositories;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieArchiveTemplate.Controllers
{
    public class MembershipController : Controller
    {
        private MembershipRepository membership;

        public MembershipController()
        {
            membership = new MembershipRepository();
        }

        // GET: Users
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(NLoginModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                model.Password = MD5Generate.GetMd5Hash(model.Password);
                var loginResult = membership.Login(model);
                if (loginResult.IsSuccessful)
                {
                    Session["User"] = loginResult.Data.ID.ToString();

                    if (!string.IsNullOrEmpty(returnUrl))
                        return Redirect(returnUrl);
                    else
                        return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", loginResult.Message);
                }
            }

            return View();
        }


        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Register(User model, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                model.Password = MD5Generate.GetMd5Hash(model.Password);
                model.RegisterDate = DateTime.Now;
                model.MemberType = MemberType.User;
                if (file != null && file.ContentLength > 0)
                {
                    MemoryStream memoryStream = file.InputStream as MemoryStream;
                    if (memoryStream == null)
                    {
                        memoryStream = new MemoryStream();
                        file.InputStream.CopyTo(memoryStream);
                    }
                    model.ProfilPicture = memoryStream.ToArray();
                }

                var registerResult = membership.Register(model);
                if (registerResult.IsSuccessful)
                {
                    ViewBag.State = registerResult.Message;
                }
                else
                {
                    ModelState.AddModelError("", registerResult.Message);
                }
            }
         
            return RedirectToAction("Login");
        }


        public ActionResult Logout()
        {
            Session.Remove("User");

            return RedirectToAction("Index", "Home");
        }
    }
}

MovieArchiveTemplate/Views/Membership/Login.cshtml
@model MovieArchiveTemplate.Models.ViewModels.NLoginModel

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";

    if (Session["User"] != null)
    {
        Response.Redirect("~/Profile");
    }
}

@section additionalJs {
    @if (ViewBag.LoginSuccess != null && ViewBag.LoginSuccess)
    {
        <div id="wrapper">
            <div id="message-sent">
                <div id="close-button">
                    <span>X</span>
                </div>
                <span>Başarıyla giriş yapıldı.</span>
            </div>
        </div>
    }

    <script>
        $('#wrapper').click(function () {
            $(this).fadeOut('slow');
        });
    </script>
}


<!-- Blog Section -->
<section id="blog">
    <div class="container">

        <div class="row" style="text-align: center">
            <div class="col-lg-12 wp2 delay-05s">
                <div class="sidebar-widget content_top">
                    <h2>@MovieArchiveTemplate.Resource.lang.GİRİŞ</h2>
                </div>
            </div>
        </div>

        <div class="row">
            <!-- Login -->
            <div class="col-lg-12 wp2 delay-05s">
                @using (Html.BeginForm("Login", "Membership", FormMethod.Post, new { @class = "form-section", role = "form", @style = "margin-left: 28%; margin-right: 28%" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-group">

                        <div class="row" style="margin: 3%">
                            <div class="col-lg-12">
                                @Html.ValidationSummary()
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-4">
                                @Html.Label(@MovieArchiveTemplate.Resource.lang.EMail)
                            </div>
                            <div class="col-lg-8">
                                @Html.TextBoxFor(model => model.EMail, new { @class = "form-control" })
                            </div>
                        </div>
                        <br />

                        <div class="row">
                            <div class="col-lg-4">
                                @Html.Label(@MovieArchiveTemplate.Resource.lang.Şifre)
                            </div>
                            <div class="col-lg-8">
                                @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                            </div>
                        </div>
                        <br />
                        <br />

                        <div class="row">
                            <div class="col-lg-4"></div>
                            <div class="col-lg-1">
                                <input type="submit" value="@MovieArchiveTemplate.Resource.lang.GİRİŞ" class="btn" />
                            </div>
                        </div>
                        <br />
                        <br />
                    </div>
                }
            </div><!-- /.col-lg-6 -->

        </div><!-- /.row -->

    </div><!-- /.container -->
</section><!-- /#blog --> 

MovieArchiveTemplate/Views/Membership/Register.cshtml
@model MovieArchiveTemplate.Models.User

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="blog">
    <div class="container">

        <div class="row" style="text-align: center">
            <div class="col-lg-12 wp2 delay-05s">
                <div class="sidebar-widget content_top">
                    <h2>@MovieArchiveTemplate.Resource.lang.KayıtOl</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <!-- Login -->
            <div class="col-lg-12 wp2 delay-05s">

                @using (Html.BeginForm("Register", "Membership", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <div class="row" style="margin: 3%">
                            <div class="col-lg-12">
                                @Html.ValidationSummary()
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-4">
                                @Html.Label(MovieArchiveTemplate.Resource.lang.ProfilFoto)
                            </div>
                            <div class="col-lg-8">
                                @Html.EditorFor(model => model.ProfilPicture, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ProfilPicture, "", new { @class = "text-danger" })
                                <input type="file" name="file" class="form-control" />
                            </div>
                        </div>
                        <br />

                        <div class="row">
                            <div class="col-lg-4">
                                @Html.Label(MovieArchiveTemplate.Resource.lang.Ad)
                            </div>
                            <div class="col-lg-8">
                                @Html.EditorFor(model => model.FName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.FName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />

                        <div class="row">
                            <div class="col-lg-4">
                                @Html.Label(MovieArchiveTemplate.Resource.lang.SoyAd)
                            </div>
                            <div class="col-lg-8">
                                @Html.EditorFor(model => model.LName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.LName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />

                        <div class="row">
                            <div class="col-lg-4">
                                @Html.Label(MovieArchiveTemplate.Resource.lang.EMail)
                            </div>
                            <div class="col-lg-8">
                                @Html.EditorFor(model => model.EMail, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.EMail, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />

                        <div class="row">
                            <div class="col-lg-4">
                                @Html.Label(MovieArchiveTemplate.Resource.lang.Şifre)
                            </div>
                            <div class="col-lg-8">
                                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />

                        <div class="row">
                            <div class="col-lg-4">
                                @Html.Label(MovieArchiveTemplate.Resource.lang.Telefon)
                            </div>
                            <div class="col-lg-8">
                                @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <br />

                        <div class="row">
                            <center><input type="submit" value="@MovieArchiveTemplate.Resource.lang.Kaydet" class="btn btn-default" /></center>
                        </div>
                    </div>
                }
            </div><!-- /.col-lg-6 -->

        </div><!-- /.row -->


    </div>
</section>