MovieArchiveTemplate/Areas/Admin/Controllers/HomeController.cs
using MovieArchiveTemplate.Models.ViewModels;
using MovieArchiveTemplate.Repositories;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieArchiveTemplate.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        private MovieArchiveDB db = new MovieArchiveDB();

        // GET: Admin/Home
        public ActionResult Index()
        {
            ViewBag.AdminCount = db.User.Where(u => u.MemberType == MemberType.Admin).Count();
            ViewBag.MovieCount = db.Movie.Count();
            ViewBag.GenreCount = db.Genre.Count();
            ViewBag.UserCount = db.User.Count();

            return View();
        }

        public ActionResult Logout()
        {
            Session.Remove("User");

            return RedirectToAction("Index", "../Home");
        }


        public ActionResult ChangeCulture(string lang, string returnUrl)
        {
            Session["Culture"] = new CultureInfo(lang);

            return Redirect(returnUrl);
        }
    }
}

MovieArchiveTemplate/Areas/Admin/Controllers/UsersController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MovieArchiveTemplate.Models;
using MovieArchiveTemplate.Repositories;

namespace MovieArchiveTemplate.Areas.Admin.Controllers
{
    public class UsersController : Controller
    {
        private MovieArchiveDB db = new MovieArchiveDB();

        // GET: Admin/Users
        public ActionResult Index(int? page, string sorting)
        {
            var userList = db.User.ToList();


            #region [SIRALAMA]
            // ------------------- SIRALAMA --------------------

            // Burada controller çağrılırken "?sorting=xxx_ifade" şeklinde parametre gelir.
            if (string.IsNullOrEmpty(sorting))
            {
                sorting = "LNameAsc";
            }
            ViewBag.RegisterDateSortParam = sorting == "RegisterDateAsc" ? "RegisterDateDesc" : "RegisterDateAsc";
            ViewBag.LNameSortParam = sorting == "LNameDesc" ? "LNameAsc" : "LNameDesc";

            switch (sorting)
            {
                case "RegisterDateAsc":
                    userList = userList.OrderBy(m => m.RegisterDate).ToList();
                    ViewBag.CurrentSortParam = "RegisterDateDesc";
                    ViewBag.CurrentDDLText = "Register Date";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-desc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda çoktan aza sıralar.";
                    break;
                case "RegisterDateDesc":
                    userList = userList.OrderByDescending(m => m.RegisterDate).ToList();
                    ViewBag.CurrentSortParam = "RegisterDateAsc";
                    ViewBag.CurrentDDLText = "Register Date";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-asc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda azdan çoka sıralar.";
                    break;
                case "LNameAsc":
                    userList = userList.OrderBy(m => m.LName).ToList();
                    ViewBag.CurrentSortParam = "LNameDesc";
                    ViewBag.CurrentDDLText = "Last Name";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-desc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda çoktan aza sıralar.";
                    break;
                case "LNameDesc":
                    userList = userList.OrderByDescending(m => m.LName).ToList();
                    ViewBag.CurrentSortParam = "LNameAsc";
                    ViewBag.CurrentDDLText = "Last Name";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-asc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda azdan çoka sıralar.";
                    break;
                default:
                    userList = userList.OrderBy(m => m.LName).ToList();
                    ViewBag.CurrentSortParam = "LNameDesc";
                    ViewBag.CurrentDDLText = "Last Name";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-desc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda çoktan aza sıralar.";
                    break;
            }
            // ------------------- SIRALAMA --------------------
            #endregion

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View("Index", userList.ToPagedList(pageNumber, pageSize));
        }

        // GET: Admin/Users/Details?userID=id
        public ActionResult Details(int? userID)
        {
            if (userID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.User.Find(userID);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Admin/Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(User user)
        {
            if (ModelState.IsValid)
            {
                db.User.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Admin/Users/Edit?userID=id
        public ActionResult Edit(int? userID)
        {
            if (userID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.User.Find(userID);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Admin/Users/Edit?userID=id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Admin/Users/Delete?userID=id
        public ActionResult Delete(int? userID)
        {
            if (userID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.User.Find(userID);
            if (user == null)
            {
                return HttpNotFound();
            }
            db.User.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MovieArchiveTemplate/Controllers/MoviesController.cs
using MovieArchiveTemplate.Models.ViewModels;
using MovieArchiveTemplate.Repositories;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieArchiveTemplate.Controllers
{
    public class MoviesController : Controller
    {
        MovieArchiveDB db = new MovieArchiveDB();

        public ActionResult MoviesThisWeek(int? page, string sorting)
        {
            var contentMovies = db.Movie.OrderByDescending(m => m.ReleaseDate).ToList();
            NMainPageDTO obj = new NMainPageDTO();
            obj.Categories = db.Genre.OrderBy(c => c.GenreName).ToList();
            obj.FutureMovies = db.Movie.OrderByDescending(m => (m.ReleaseDate >= DateTime.Now)).Take(3).ToList();
            obj.RandomMovies = (from result in contentMovies.AsEnumerable() orderby Guid.NewGuid() select result).Take(3).ToList();

            ViewBag.MainPageDTO = obj;

            #region [SIRALAMA]
            // ------------------- SIRALAMA --------------------

            // Burada controller çağrılırken "?sorting=xxx_ifade" şeklinde parametre gelir.
            if (string.IsNullOrEmpty(sorting))
            {
                sorting = "ReleaseDateDesc";
            }
            ViewBag.ReleaseDateSortParam = sorting == "ReleaseDateAsc" ? "ReleaseDateDesc" : "ReleaseDateAsc";
            ViewBag.RaitingSortParam = sorting == "RaitingDesc" ? "RaitingAsc" : "RaitingDesc";

            // Gelen sıralama ifadesine göre sıralama yapılır.
            DateTime temp = DateTime.Now.AddDays(-7);
            switch (sorting)
            {
                case "ReleaseDateAsc":
                    contentMovies = db.Movie.Where(m => (m.ReleaseDate >= temp && m.ReleaseDate <= DateTime.Now)).OrderBy(m => m.ReleaseDate).ToList();
                    ViewBag.CurrentSortParam = "ReleaseDateDesc";
                    ViewBag.CurrentDDLText = "Release Date";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-desc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda çoktan aza sıralar.";
                    break;
                case "ReleaseDateDesc":
                    contentMovies = db.Movie.Where(m => (m.ReleaseDate >= temp && m.ReleaseDate <= DateTime.Now)).OrderByDescending(m => m.ReleaseDate).ToList();
                    ViewBag.CurrentSortParam = "ReleaseDateAsc";
                    ViewBag.CurrentDDLText = "Release Date";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-asc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda azdan çoka sıralar.";
                    break;
                case "RaitingAsc":
                    contentMovies = db.Movie.Where(m => (m.ReleaseDate >= temp && m.ReleaseDate <= DateTime.Now)).OrderBy(m => m.Raiting).ToList();
                    ViewBag.CurrentSortParam = "RaitingDesc";
                    ViewBag.CurrentDDLText = "Raiting";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-desc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda çoktan aza sıralar.";
                    break;
                case "RaitingDesc":
                    contentMovies = db.Movie.Where(m => (m.ReleaseDate >= temp && m.ReleaseDate <= DateTime.Now)).OrderByDescending(m => m.Raiting).ToList();
                    ViewBag.CurrentSortParam = "RaitingAsc";
                    ViewBag.CurrentDDLText = "Raiting";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-asc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda azdan çoka sıralar.";
                    break;
                default:
                    contentMovies = db.Movie.Where(m => (m.ReleaseDate >= temp && m.ReleaseDate <= DateTime.Now)).OrderByDescending(m => m.ReleaseDate).ToList();
                    ViewBag.CurrentSortParam = "ReleaseDateAsc";
                    ViewBag.CurrentDDLText = "Release Date";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-asc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda azdan çoka sıralar.";
                    break;
            }
            // ------------------- SIRALAMA --------------------
            #endregion


            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View("MoviesThisWeek", contentMovies.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult MoviesComingSoon(int? page, string sorting)
        {
            var contentMovies = db.Movie.Where(m => m.ReleaseDate >= DateTime.Now).ToList();
            NMainPageDTO obj = new NMainPageDTO();
            obj.Categories = db.Genre.OrderBy(c => c.GenreName).ToList();
            obj.FutureMovies = db.Movie.Where(m => (m.ReleaseDate >= DateTime.Now)).Take(3).ToList();
            obj.RandomMovies = (from result in contentMovies.AsEnumerable() orderby Guid.NewGuid() select result).Take(3).ToList();

            ViewBag.MainPageDTO = obj;

            #region [SIRALAMA]
            // ------------------- SIRALAMA --------------------

            // Burada controller çağrılırken "?sorting=xxx_ifade" şeklinde parametre gelir.
            if (string.IsNullOrEmpty(sorting))
            {
                sorting = "ReleaseDateDesc";
            }
            ViewBag.ReleaseDateSortParam = sorting == "ReleaseDateAsc" ? "ReleaseDateDesc" : "ReleaseDateAsc";
            ViewBag.RaitingSortParam = sorting == "RaitingDesc" ? "RaitingAsc" : "RaitingDesc";

            // Gelen sıralama ifadesine göre sıralama yapılır.
            switch (sorting)
            {
                case "ReleaseDateAsc":
                    contentMovies = db.Movie.Where(m => (m.ReleaseDate >= DateTime.Now)).OrderBy(m => m.ReleaseDate).ToList();
                    ViewBag.CurrentSortParam = "ReleaseDateDesc";
                    ViewBag.CurrentDDLText = "Release Date";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-desc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda çoktan aza sıralar.";
                    break;
                case "ReleaseDateDesc":
                    contentMovies = db.Movie.Where(m => (m.ReleaseDate >= DateTime.Now)).OrderByDescending(m => m.ReleaseDate).ToList();
                    ViewBag.CurrentSortParam = "ReleaseDateAsc";
                    ViewBag.CurrentDDLText = "Release Date";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-asc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda azdan çoka sıralar.";
                    break;
                case "RaitingAsc":
                    contentMovies = db.Movie.Where(m => (m.ReleaseDate >= DateTime.Now)).OrderBy(m => m.Raiting).ToList();
                    ViewBag.CurrentSortParam = "RaitingDesc";
                    ViewBag.CurrentDDLText = "Raiting";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-desc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda çoktan aza sıralar.";
                    break;
                case "RaitingDesc":
                    contentMovies = db.Movie.Where(m => (m.ReleaseDate >= DateTime.Now)).OrderByDescending(m => m.Raiting).ToList();
                    ViewBag.CurrentSortParam = "RaitingAsc";
                    ViewBag.CurrentDDLText = "Raiting";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-asc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda azdan çoka sıralar.";
                    break;
                default:
                    contentMovies = db.Movie.Where(m => (m.ReleaseDate >= DateTime.Now)).OrderByDescending(m => m.ReleaseDate).ToList();
                    ViewBag.CurrentSortParam = "ReleaseDateAsc";
                    ViewBag.CurrentDDLText = "Release Date";
                    ViewBag.CurrentArrow = "fa fa-sort-amount-asc";
                    ViewBag.ResortBtnAlt = "Tıkladığınızda azdan çoka sıralar.";
                    break;
            }
            // ------------------- SIRALAMA --------------------
            #endregion

            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View("MoviesComingSoon", contentMovies.ToPagedList(pageNumber, pageSize));
        }


        public ActionResult MovieDetails(int movieID)
        {
            var contentMovies = db.Movie.Where(m => m.ReleaseDate >= DateTime.Now).ToList();
            NMainPageDTO obj = new NMainPageDTO();
            obj.Categories = db.Genre.OrderBy(c => c.GenreName).ToList();
            obj.FutureMovies = db.Movie.Where(m => (m.ReleaseDate >= DateTime.Now)).Take(3).ToList();
            obj.RandomMovies = (from result in contentMovies.AsEnumerable() orderby Guid.NewGuid() select result).Take(3).ToList();

            ViewBag.MainPageDTO = obj;

            var movie = db.Movie.Where(m => m.MovieID == movieID).FirstOrDefault();

            return View(movie);
        }


        public ActionResult MovieList(int genreID, int? page, string sorting)
        {
            var movies = db.Movie.Where(m => m.ReleaseDate >= DateTime.Now).ToList();
            NMainPageDTO obj = new NMainPageDTO();
            obj.Categories = db.Genre.OrderBy(c => c.GenreName).ToList();
            obj.FutureMovies = db.Movie.Where(m => (m.ReleaseDate >= DateTime.Now)).Take(3).ToList();
            obj.RandomMovies = (from result in movies.AsEnumerable() orderby Guid.NewGuid() select result).Take(3).ToList();

            ViewBag.MainPageDTO = obj;

            var tempGenre = db.Genre.Where(g => g.GenreID == genreID).First();
            ViewBag.Title = tempGenre.GenreName;

            var contentMovies = tempGenre.Movie.ToList();
            #region [SIRALAMA]
            // ------------------- SIRALAMA --------------------

            // Burada controller çağrılırken "?sorting=xxx_ifade" şeklinde parametre gelir.
            if (string.IsNullOrEmpty(sorting))
            {
                sorting = "ReleaseDateDesc";
            }

MovieArchiveTemplate/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Movie Archive Admin";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="container-fluid">
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                @MovieArchiveTemplate.Resource.lang.Dashboard <small>@MovieArchiveTemplate.Resource.lang.staticover</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> @MovieArchiveTemplate.Resource.lang.Dashboard
                </li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-comments fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">@ViewBag.GenreCount</div>
                            <div>@MovieArchiveTemplate.Resource.lang.GenreCount</div>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("Index", "Genres")">
                    <div class="panel-footer">
                        <span class="pull-left">@MovieArchiveTemplate.Resource.lang.DetayGöster</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-green">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-tasks fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">@ViewBag.MovieCount</div>
                            <div>@MovieArchiveTemplate.Resource.lang.MovieCount</div>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("Index", "Movies")">
                    <div class="panel-footer">
                        <span class="pull-left">@MovieArchiveTemplate.Resource.lang.DetayGöster</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-yellow">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-shopping-cart fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">@ViewBag.UserCount</div>
                            <div>@MovieArchiveTemplate.Resource.lang.UserCount</div>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("Index", "Users")">
                    <div class="panel-footer">
                        <span class="pull-left">@MovieArchiveTemplate.Resource.lang.DetayGöster</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-red">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-support fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">@ViewBag.AdminCount</div>
                            <div>@MovieArchiveTemplate.Resource.lang.AdminCount</div>
                        </div>
                    </div>
                </div>
                <a href="@Url.Action("Index", "Users")">
                    <div class="panel-footer">
                        <span class="pull-left">@MovieArchiveTemplate.Resource.lang.DetayGöster</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <!-- /.row -->
</div>
<!-- /.container-fluid -->